Repository PaloAltoNetworks/pan-os-upgrade-assurance, pull requests merged in 2023-07, with the labels that each got.

#74 feat: add check to verify cert requirements
  docs/panos-upgrade-assurance/api/check_firewall.md
  docs/panos-upgrade-assurance/api/exceptions.md
  docs/panos-upgrade-assurance/api/firewall_proxy.md
  docs/panos-upgrade-assurance/api/utils.md
  docs/panos-upgrade-assurance/configuration_details.mdx
  examples/low_level_methods/run_low_level_methods.py
  examples/readiness_checks/run_readiness_checks.py
  panos_upgrade_assurance/check_firewall.py
  panos_upgrade_assurance/exceptions.py
  panos_upgrade_assurance/firewall_proxy.py
  panos_upgrade_assurance/utils.py
  pyproject.toml
Labels: enhancement, codebase

#77 fix: snapshot comparison with no common keys
  panos_upgrade_assurance/snapshot_compare.py
Labels: bug, codebase

#80 ci: introduce docker images build and push to GHCR
  .github/actions/discover_python_version/action.yml
  .github/workflows/docker.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/sub_docs.yml
  .github/workflows/sub_format.yml
  .gitignore
  Dockerfile
  docker_image/Dockerfile
  docker_image/build.sh
  docs/panos-upgrade-assurance.mdx
  docs/panos-upgrade-assurance/installation.mdx
Labels: ci
